project_id = "ifetofkhyblyijghuwzs"

[functions.ai-analyze]
verify_jwt = false

[functions.stock-analysis]
verify_jwt = false

[functions.binance-data]
verify_jwt = false

[functions.polygon-market-data]
verify_jwt = false

[functions.ai-market-analysis]
verify_jwt = false

[functions.realtime-market-stream]
verify_jwt = false

[functions.polygon-chart-data]
verify_jwt = false

[functions.ai-chart-analysis]
verify_jwt = false