project_id = "ifetofkhyblyijghuwzs"

[functions.ai-analyze]
verify_jwt = false

[functions.ai-chart-analysis]
verify_jwt = false

[functions.ai-generate-analysis]
verify_jwt = false

[functions.ai-market-analysis]
verify_jwt = false

[functions.news-signal-analysis]
verify_jwt = false

[functions.macro-market-analysis]
verify_jwt = false

[functions.market-sentiment]
verify_jwt = false

[functions.binance-data]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.check-trade-outcomes]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.finnhub-data]
verify_jwt = false

[functions.kraken-orderbook]
verify_jwt = false

[functions.metrics-log]
verify_jwt = false

[functions.news-fetch]
verify_jwt = false

[functions.news-gate]
verify_jwt = false

[functions.news-insights]
verify_jwt = false

[functions.polygon-candles]
verify_jwt = false

[functions.polygon-chart-data]
verify_jwt = false

[functions.polygon-indicators]
verify_jwt = false

[functions.polygon-debug]
verify_jwt = false

[functions.polygon-market-data]
verify_jwt = false

[functions.polygon-search]
verify_jwt = false

[functions.quant-data]
verify_jwt = false

[functions.realtime-market-stream]
verify_jwt = false

[functions.stock-analysis]
verify_jwt = false